import React, { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";
import Table from "@/components/Table";
import { Box, Button, Modal } from "@mui/material";
type User = {
  id: string;
  name: string;
};
type Photo = {
  id: string;
  url: string;
};

const style = {
  position: "absolute" as "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 400,
  bgcolor: "background.paper",
  border: "2px solid #000",
  boxShadow: 24,
  p: 4,
};
function Index() {
  const [profiles, setProfiles] = useState<User[]>();
  const [valuePhoto, setValuePhoto] = useState<string>("");
  const [photos, setPhotos] = useState<Photo[]>([]);
  const allUsers = async () => {
    const res = await axios.get(
      `${process.env.NEXT_PUBLIC_HOST}:${process.env.NEXT_PUBLIC_PORT}/profile`
    );
    setProfiles(res.data);
  };
  const allPhotos = async () => {
    const res = await axios.get(
      `${process.env.NEXT_PUBLIC_HOST}:${process.env.NEXT_PUBLIC_PORT}/photo`
    );
    setPhotos(res.data);
  };

  const onSelectPhoto = (event: React.ChangeEvent<HTMLSelectElement>) => {
    // console.log("User Selected the Photo - ", event.target.value);
    setValuePhoto(event.target.value);
  };
  const Asignar = (id: string) => {
    AsignPhoto(id);
  };
  const AsignPhoto = async (id: string) => {
    const res = await axios({
      method: "put",
      url: `${process.env.NEXT_PUBLIC_HOST}:${process.env.NEXT_PUBLIC_PORT}/photo/asign/${id}`,
      data: {
        photoId: valuePhoto,
      },
    });
  };
  const [open, setOpen] = React.useState<boolean>(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  useEffect(() => {
    allUsers();
    allPhotos();
  }, []);
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <table className="table">
          <thead>
            <tr>
              <th scope="col">usuario</th>
              <th scope="col">asignar</th>
            </tr>
          </thead>
          <tbody>
            {profiles?.map((profile, index) => (
              <tr key={index}>
                <td>{profile.name}</td>
                <td className="asignar">
                  <Button
                    color="primary"
                    variant="contained"
                    onClick={handleOpen}
                  >
                    Asignar
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <hr></hr>
        <br></br>
      </main>
      <Modal
        open={open}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <Box sx={style}>
          <Button onClick={handleClose}>Asignar</Button>
          <table className="table">
            <thead>
              <tr>
                <th scope="col">auto</th>
              </tr>
            </thead>
            <tbody>
              {photos?.map((photo, index) => (
                <tr key={index}>
                  <td>{photo.url}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <hr></hr>
          <br></br>
        </Box>
      </Modal>
    </>
  );
}

export default Index;
