import React, { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";
import {
  Box,
  Button,
  Modal,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
} from "@mui/material";
import TableContainer from "@mui/material/TableContainer";
type User = {
  id: string;
  name: string;
};
type Photo = {
  id: string;
  url: string;
};

const style = {
  position: "absolute" as "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 400,
  bgcolor: "background.paper",
  border: "2px solid #000",
  boxShadow: 24,
  p: 4,
};
const onHandleModal = (photoId: string) => {
  console.log(`abre Modal ${photoId}`);
};
const onDelete = (photoId: string) => {
  console.log(`borra auto ${photoId}`);
};
function Index() {
  const [photos, setPhotos] = useState<Photo[]>([]);
  const allPhotos = async () => {
    const res = await axios.get(
      `${process.env.NEXT_PUBLIC_HOST}:${process.env.NEXT_PUBLIC_PORT}/photo`
    );
    setPhotos(res.data);
  };
  useEffect(() => {
    allPhotos();
  }, []);
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <TableContainer>
          <Table sx={{ minWidth: 650 }}>
            <TableHead>
              <TableRow>
                <TableCell>usuario</TableCell>
                <TableCell>asignar</TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {photos?.map((photo, index) => (
                <TableRow key={index}>
                  <TableCell>{photo.url}</TableCell>
                  <TableCell>
                    <Button onClick={() => onHandleModal(photo.id)}>
                      Editar
                    </Button>
                    <Button onClick={() => onDelete(photo.id)}>Eliminar</Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
        <hr></hr>
        <br></br>
      </main>
    </>
  );
}

export default Index;
