import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>


        <div className={styles.grid}>
          <Link href="/users">
            <h2 className={inter.className}>
              Users <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List of ours users.
            </p>
          </Link>
          <Link href="/photos">
            <h2 className={inter.className}>
              Photos <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List all Photos.
            </p>
          </Link>


        </div>
      </main>
    </>
  )
}
