import React, { useEffect, useState } from "react";
import Head from "next/head";
import axios from "axios";
type User = {
  id: string;
  name: string;
};

function Index() {
  const [profiles, setProfiles] = useState<User[]>();
  const [valuePhoto, setValuePhoto] = useState<string>("");
  const allUsers = async () => {
    const res = await axios.get(
      `${process.env.NEXT_PUBLIC_HOST}:${process.env.NEXT_PUBLIC_PORT}/profile`
    );
    setProfiles(res.data);
  };

  const options = ["One", "Two", "Three", "Four", "Five"];
  const onOptionChangeHandler = (
    event: React.ChangeEvent<HTMLSelectElement>
  ) => {
    console.log("User Selected Value - ", event.target.value);
    setValuePhoto(event.target.value);
  };
  const Asignar = (id: string) => {
    AsignPhoto(id);
  };
  const AsignPhoto = async (id: string) => {
    const res = await axios({
      method: "put",
      url: `${process.env.NEXT_PUBLIC_HOST}:${process.env.NEXT_PUBLIC_PORT}/photo/asign/${id}`,
      data: {
        photoId: valuePhoto,
      },
    });
  };
  useEffect(() => {
    allUsers();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        {profiles?.map((profile, index) => (
          <div key={index}>
            <p>{profile.name}</p>
            <select onChange={onOptionChangeHandler}>
              <option>Please choose one option</option>
              {options.map((option, index) => {
                return <option key={index}>{option}</option>;
              })}
            </select>
            <button
              onClick={() => {
                Asignar(profile.id);
              }}
            >
              Asignar
            </button>
          </div>
        ))}
      </main>
    </>
  );
}

export default Index;
