import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
function index() {
    const allUsers = async () => {
        const res = await fetch(`${process.env.NEXT_PUBLIC_HOST}:${process.env.NEXT_PUBLIC_PORT}/profile`)
        const cars = await res.json();
        console.log(cars);
    }
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>


                <div className={styles.grid}>
                    <button onClick={allUsers}>Clickeame</button>
                </div>
            </main>
        </>

    )
}

export default index

